### PR TITLE
Allow monitors to be initialized as disabled

### PR DESCRIPTION
**Pull request by kyork-cl**
Adding support for changes at zettajs/zetta-scientist#4

### CODE REVIEW

**Comment by AdamMagaluk** [comment]
@kyork-cl We also need to handle the case when calling `config.stream('value', this.handler, { disable: true })` so both `config.monitor()` and `config.stream()` can be called with the disabled flag.

**Comment by kyork-cl** [comment]
Ok.  I haven't messed with streams too much, is it fine to just put the disableStream call before the return like I did for monitors, or do I need to suppress the `handler.call()` as well?

**Comment by AdamMagaluk** [comment]
So should be able to call `.disableStream` right before handler.call() in _initStream

**Comment by kyork-cl** [comment]
Done

**Comment by AdamMagaluk** [comment]
Looks good to me.

**Comment by AdamMagaluk** [comment]
Closing this PR as i created #17  with backwards compatibility support. Going to table the device_config issue for now and create a change later. Filed an issue here on the main zetta project. zettajs/zetta#290

**Pull request closed without merging**
